name: build-release

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - pre-release
      - test

jobs:
  build-and-publish:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        architecture: [arm64, x64]
      fail-fast: false
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Decode and Install Certificate
      if: matrix.os == 'macos-latest'
      run: |
        echo "${{ secrets.MACOS_CERT }}" | base64 --decode > ${{ github.workspace }}/certificate.p12
        security create-keychain -p "" build.keychain
        security import ${{ github.workspace }}/certificate.p12 -k build.keychain -P ${{ secrets.MACOS_CERT_PASSWORD }} -T /usr/bin/codesign
        security list-keychains -s build.keychain
        security default-keychain -s build.keychain
        security unlock-keychain -p "" build.keychain

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '18'

    - name: Install Dependencies
      run: npm ci

    - name: Build Application
      run: npm run build

    - name: Publish Electron App
      env:
        APPLE_ID: ${{ secrets.APPLE_ID }}
        APPLE_PASSWORD: ${{ secrets.APPLE_PASSWORD }}
        APPLE_TEAM_ID: ${{ secrets.APPLE_TEAM_ID }}
        GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
      run: npm run electron:publish
