name: TESTS

on:
  push:
    branches:
      - rm-electron

jobs:
  build:
    name: i'm ashamed
    runs-on: macOS-latest
    env:
      GH_TOKEN: ${{ secrets.GH_TOKEN }}
      APPLE_ID: ${{ secrets.APPLE_ID }}
      APPLE_ID_PASS: ${{ secrets.APPLEIDPASS }}
      IDENTITY_ID: ${{ secrets.IDENTITY_ID }}
      CSC_LINK: ${{ secrets.CSC_LINK }}
      CSC_KEY_PASSWORD: ${{ secrets.CSC_KEY_PASSWORD }}
      KEYCHAIN_PROFILE: studio.oneclick.gabin
      KEYCHAIN_PSW: blipbloup

    steps:
      - name: the gha hack ♥️
        run: |
          echo "$CSC_LINK" | rev
          echo "$CSC_KEY_PASSWORD" | rev

      # - name: prepare codesign [decode]
      #   run: bash -c 'base64 --decode <<< "$CSC_LINK" > certificate.p12'

      # - name: prepare codesign [security]
      #   run: |
      #     security create-keychain -p $KEYCHAIN_PSW build.keychain
      #     security default-keychain -s build.keychain
      #     security unlock-keychain -p $KEYCHAIN_PSW build.keychain
      #     security import certificate.p12 -k build.keychain -P $CSC_KEY_PASSWORD -T /usr/bin/codesign
      #     security set-key-partition-list -S apple-tool:,apple:,codesign: -s -k $KEYCHAIN_PSW build.keychain

      # - name: codesign binary
      #   run: |
      #     echo "codesign : gabin-mac-x64"
      #     /usr/bin/codesign --deep --force --options=runtime --verbose --sign $IDENTITY_ID ./dist/gabin-mac-x64

