name: Create Release

on:
  push:
    branches:
      - rm-electron

jobs:
  create:
    name: Create release
    runs-on: ubuntu-latest
    env:
      tag_prefix: nightly-tag-
      release_prefix: Release 
    outputs:
      tag_name: ${{ env.tag_prefix }}${{ steps.date.outputs.NOW }}
      release_name: ${{ env.release_prefix }}${{ steps.date.outputs.NOW }}
    steps:
      - name: Get current date
        id: date
        run: |
          echo "NOW=$(date +'%Y%m%d')" >> $GITHUB_OUTPUT

  # build:
  #   name: Build & upload release
  #   runs-on: ubuntu-latest
  #   needs: create

  #   steps:
  #     - uses: actions/checkout@v3

  #     - name: Install ALSA API
  #       run: sudo apt-get install -y libasound2-dev

  #     - uses: actions/setup-node@v3
  #       name: Install Node.js
  #       with:
  #         node-version: 18

  #     - uses: pnpm/action-setup@v2
  #       name: Install pnpm
  #       id: pnpm-install
  #       with:
  #         version: 7
  #         run_install: false

  #     - name: Get pnpm store directory
  #       id: pnpm-cache
  #       shell: bash
  #       run: |
  #         echo "STORE_PATH=$(pnpm store path)" >> $GITHUB_OUTPUT

  #     - uses: actions/cache@v3
  #       name: Setup pnpm cache
  #       with:
  #         path: ${{ steps.pnpm-cache.outputs.STORE_PATH }}
  #         key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
  #         restore-keys: |
  #           ${{ runner.os }}-pnpm-store-

  #     - name: Install dependencies
  #       run: pnpm installAll

  #     - name: fetch pkg macOS
  #       run: pnpm run pkg:fetch

  #     - name: build macOS [BIN]
  #       run: pnpm run pkg:mac

  #     - name: what is there
  #       run: |
  #         ls ./dist

  #     - name: build macOS [DMG]
  #       run: pnpm run pkg:mac:dmg

  #     - name: upload release macOS
  #       uses: ncipollo/release-action@v1
  #       id: upload_release_macos
  #       with:
  #         token: ${{ secrets.GH_TOKEN }}
  #         name: ${{ needs.create.outputs.release_name }}
  #         tag: ${{ needs.create.outputs.tag_name }}
  #         allowUpdates: true
  #         artifacts: "./dist/Gabin-*.dmg,./dist/gabin-*"
  #         draft: true


  build:
    name: Build & upload release [${{ matrix.os }}]
    runs-on: ${{ matrix.os }}
    needs: create
    env:
      MACOS_CERTIFICATE: ${{ secrets.APPLEIDPASS }}
      MACOS_CERTIFICATE_PWD: ${{ secrets.APPLE_ID }}
      GH_TOKEN: ${{ secrets.GH_TOKEN }}
      APPLE_ID: ${{ secrets.APPLE_ID }}
      APPLE_ID_PASS: ${{ secrets.APPLEIDPASS }}
      IDENTITY_ID: ${{ secrets.IDENTITY_ID }}
      CSC_LINK: ${{ secrets.CSC_LINK }}
      CSC_KEY_PASSWORD: ${{ secrets.CSC_KEY_PASSWORD }}
      KEYCHAIN_PSW: blipbloup

    strategy:
      matrix:
        os: [macOS-latest]
        # os: [windows-latest, macOS-latest]

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        name: Install Node.js
        with:
          node-version: 18

      - uses: pnpm/action-setup@v2
        name: Install pnpm
        id: pnpm-install
        with:
          version: 7
          run_install: false

      - name: Get pnpm store directory
        id: pnpm-cache
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path)" >> $GITHUB_OUTPUT

      - uses: actions/cache@v3
        name: Setup pnpm cache
        with:
          path: ${{ steps.pnpm-cache.outputs.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      #TODO - Remove this once https://github.com/electron-userland/electron-builder/issues/6933#issuecomment-1213438889 is resolved
      - name: Get pnpm file path
        if: matrix.os == 'windows-latest'
        shell: bash
        run: |
          PNPM_VERSION=$(pnpm -v)
          echo "PNPM_FILE=\"/c/users/runneradmin/setup-pnpm/node_modules/.pnpm/pnpm@$PNPM_VERSION/node_modules/pnpm/bin/pnpm.cjs\"" >> $GITHUB_ENV

      #TODO - Remove this once https://github.com/electron-userland/electron-builder/issues/6933#issuecomment-1213438889 is resolved
      - name: Tweak pnpm.cjs
        if: matrix.os == 'windows-latest'
        run: sed -i 's/\/usr\/bin\/env node/node/g' ${{env.PNPM_FILE}}
        shell: bash

      - name: Install dependencies
        run: pnpm installAll

      # - name: build windows
      #   if: matrix.os == 'windows-latest'
      #   run: pnpm run win:pkg

      - name: build macOS [BIN]
        if: matrix.os == 'macOS-latest'
        run: |
          pnpm run mac:pkg-pre
          pnpm run mac:pkg-x64

      - name: prepare codesign [decode]
        if: matrix.os == 'macOS-latest'
        run: bash -c 'base64 --decode <<< "$CSC_LINK" > certificate.p12'

      - name: prepare codesign [security]
        if: matrix.os == 'macOS-latest'
        run: |
          security create-keychain -p $KEYCHAIN_PSW build.keychain
          security default-keychain -s build.keychain
          security unlock-keychain -p $KEYCHAIN_PSW build.keychain
          security import certificate.p12 -k build.keychain -P $CSC_KEY_PASSWORD -T /usr/bin/codesign
          security set-key-partition-list -S apple-tool:,apple:,codesign: -s -k $KEYCHAIN_PSW build.keychain

      - name: Codesign binary
        if: matrix.os == 'macOS-latest'
        run: |
          [ -f ./dist/gabin-x64 ] && /usr/bin/codesign --deep --force --verbose --sign $IDENTITY_ID ./dist/gabin-x64
          [ -f ./dist/gabin-arm64 ] && /usr/bin/codesign --deep --force --verbose --sign $IDENTITY_ID ./dist/gabin-arm64

      - name: build macOS [APP]
        if: matrix.os == 'macOS-latest'
        run: |
          pnpm run mac:app-pre
          pnpm run mac:app-x64
          pnpm run mac:app-post

      - name: Codesign app
        if: matrix.os == 'macOS-latest'
        run: |
          [ -f ./dist/Gabin-x64.app ] && /usr/bin/codesign --deep --force --verbose --sign $IDENTITY_ID ./dist/Gabin-x64.app
          [ -f ./dist/Gabin-arm64.app ] && /usr/bin/codesign --deep --force --verbose --sign $IDENTITY_ID ./dist/Gabin-arm64.app

      - name: build macOS [DMG]
        if: matrix.os == 'macOS-latest'
        run: pnpm run mac:dmg-x64

      - name: Codesign dmg
        if: matrix.os == 'macOS-latest'
        run: |
          [ -f ./dist/Gabin-x64.dmg ] && /usr/bin/codesign --deep --force --verbose --sign $IDENTITY_ID ./dist/Gabin-x64.dmg
          [ -f ./dist/Gabin-arm64.dmg ] && /usr/bin/codesign --deep --force --verbose --sign $IDENTITY_ID ./dist/Gabin-arm64.dmg

      - name: upload release macOS
        if: matrix.os == 'macOS-latest'
        uses: ncipollo/release-action@v1
        id: upload_release_macos
        with:
          token: ${{ secrets.GH_TOKEN }}
          name: ${{ needs.create.outputs.release_name }}
          tag: ${{ needs.create.outputs.tag_name }}
          allowUpdates: true
          artifacts: "./dist/Gabin-*.dmg,./dist/gabin-*"
          draft: true

      # - name: upload release window
      #   if: matrix.os == 'windows-latest'
      #   uses: ncipollo/release-action@v1
      #   id: upload_release_win
      #   with:
      #     token: ${{ secrets.GH_TOKEN }}
      #     name: ${{ needs.create.outputs.release_name }}
      #     tag: ${{ needs.create.outputs.tag_name }}
      #     allowUpdates: true
      #     artifacts: "./dist/test-pkg-rl-win.exe"
      #     draft: true
